// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android =FirebaseOptions(
    apiKey: 'AIzaSyBTR75mhMgygxuEp7fpHiK3Ui7Gm7ISjBI',
    appId: ' 1:104309120851:android:a036fdcb281cd4e5780ba6',
    messagingSenderId: '104309120851',
    projectId: 'cold-storage-97239',
  );
  // FirebaseOptions(
  //   apiKey: 'AIzaSyC1voeOV19EjP5ti_HoJIpT_bJ00CH8qvs',
  //   appId: '1:563495710653:android:93ef10ac237cf1712aacd4',
  //   messagingSenderId: '563495710653',
  //   projectId: 'tractor-seva',
  //   storageBucket: 'tractor-seva.appspot.com',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiq7znMfykHS-p_fze6Moczg92sG0vRU4',
    appId: '1:563495710653:ios:829d1a898e9361b22aacd4',
    messagingSenderId: '563495710653',
    projectId: 'tractor-seva',
    storageBucket: 'tractor-seva.appspot.com',
    iosBundleId: 'com.tractorseva.workshop',
  );
}



// if (Platform.isIOS) {
//   await Firebase.initializeApp(
//     name: 'Workshop-iOS',
//     options: const FirebaseOptions(
//       apiKey: "",
//       appId: "1:563495710653:ios:829d1a898e9361b22aacd4",
//       messagingSenderId: "563495710653",
//       projectId: "tractor-seva",
//     ),
//   );
// } else {
//   await Firebase.initializeApp();
// }